### ISSUE TITLE
doctrine:generate:entities and OneToMany

### ISSUE THREAD

**Issue by abdeltiflouardi** [sensiolabs/SensioGeneratorBundle#10]
Hello all,

There is no way to generate OneToMany by command?

**Comment by javiereguiluz** [comment]
Recently we decided to refocus the purpose of this bundle and work only on its core features. Supporting entity associations is one of the features that we prefer to not implement yet. The alternative solution is to use third-party bundles such as SonataAdmin, which support this and many other complex features.

Therefore, I'm closing this and all the other related issues and pull requests as "won't fix". Thanks for understanding it.
