### ISSUE TITLE
Output of bundle:generate without automatic routing update confusing

### ISSUE THREAD

**Issue by igorw** [sensiolabs/SensioGeneratorBundle#117]
When running `bundle:generate` in interactive mode, if you tell it not to update the routing automatically, it returns:

> Confirm automatic update of the Routing [yes]? no
> Importing the bundle routing resource: FAILED
>
> The command was not able to configure everything automatically.  
> You must do the following changes manually.

While it makes sense to display the manual changes, the output is confusing. It failed to do something it was asked not to do in the first place.

**Comment by javiereguiluz** [comment]
This issue can be cosed as "fixed". When you answer `no` to the automatic routing update, the result is no longer a `FAILED` message:

![routing_update](https://cloud.githubusercontent.com/assets/73419/8721609/51e4b75c-2bbc-11e5-991d-7d28fa1f7022.png)
