### ISSUE TITLE
[Feature] Support of relations in the entity generator command

### ISSUE THREAD

**Issue by stof** [sensiolabs/SensioGeneratorBundle#152]
the Doctrine EntityGenerator supports relations but the interactive command of the bundle does not support defining the mapping for relations, only for columns.

**Comment by javiereguiluz** [comment]
Recently we decided to refocus the purpose of this bundle and work only on its core features. Supporting entity associations is one of the features that we prefer to not implement yet. The alternative solution is to use third-party bundles such as SonataAdmin, which support this and many other complex features.

Therefore, I'm closing this and all the other related issues and pull requests as "won't fix". Thanks for understanding it.
