### ISSUE TITLE
[generate:doctrine:entity] Give user option to update database schema

### ISSUE THREAD

**Issue by lmcd** [sensiolabs/SensioGeneratorBundle#17]
When the process is completed, give the user one final option to update the database schema. This should be the equivelant of `doctrine:schema:update --force` but for **only** the new entity.

The question should default to no.

**Comment by javiereguiluz** [comment]
I'm closing this issue as "won't fix" for the reason given by @stof and because we're trying to refocus this bundle on its core features and we don't want to complicate it with lots of uncommon features. Thanks for understanding it.
