### ISSUE TITLE
generate:doctrine:crud relies on Request::enableHttpMethodParameterOverride

### ISSUE THREAD

**Issue by Tobion** [sensiolabs/SensioGeneratorBundle#178]
See symfony/symfony#7134

**Comment by javiereguiluz** [comment]
Closing it as "won't fix". When this error was reported, Symfony was at version 2.2, where `enableHttpMethodParameterOverride` is disabled by default. However, version 2.3 and higher changed this behavior and now it's enabled by default.

**Comment by xabbuh** [comment]
@javiereguiluz Are you sure (see how [the app.php file](https://github.com/symfony/symfony-standard/blob/2.7/web/app.php#L26) from the Symfony Standard Edition looks like in 2.7)?

**Comment by javiereguiluz** [comment]
I was guided by the Symfony doc: http://symfony.com/doc/current/cookbook/routing/method_parameters.html

![method_override](https://cloud.githubusercontent.com/assets/73419/8746165/ed4a561e-2c86-11e5-95cd-9129f9033197.png)

**Comment by xabbuh** [comment]
@javiereguiluz you are right
