### ISSUE TITLE
Problem extending GenerateDoctrineCrudCommand

### ISSUE THREAD

**Issue by subnauez** [sensiolabs/SensioGeneratorBundle#179]
One of my bundle needs to override GenerateDoctrineCrudCommand behavior by providing its own Generator called MyprojectCrudGenerator.

While launching my own crud generator command, I encountered the following Exception :

```
[ErrorException]                                                                                                                                                                                                
Catchable Fatal Error: Argument 1 passed to 
Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCrudCommand::
etGenerator() must be an instance of
Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator, instance of 
Myproject\CoreBundle\GeneratorMyprojectCrudGenerator given, called in 
/Myproject/src/Myproject/CoreBundle/Command/GenerateMyprojectCrudCommand.php on line 33 and 
defined in Myproject/vendor/sensio/generator-
bundle/Sensio/Bundle/GeneratorBundle/Command/GenerateDoctrineCrudCommand.php line 246 
```

As MyprojectCrudGenerator extends GenerateDoctrineCrudCommand, I tried to extend setGenerator method inside my command class by using :

* `public function setGenerator( $generator)`
* `public function setGenerator(MyprojectCrudGenerator $generator)`

Unfortunately, I encountered a PHP Error:

```
[ErrorException]                                                                                                                                                                                                
Runtime Notice: Declaration of 
Myproject\CoreBundle\Command\GenerateMyprojectCrudCommand::setGenerator() should be 
compatible with 
Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCrudCommand::setGenerator 
(Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator $generator) in 
/Myproject/src/Myproject/CoreBundle/Command/GenerateMyprojectCrudCommand.php line 15         
```

So, I decided to patch setGenerator definition in the SensioGeneratorBundle on line 246.

```php
// vendor/sensio/generator-bundle/Sensio/Bundle/GeneratorBundle/Command/GenerateDoctrineCrudCommand.php)

public function setGenerator( $generator)
//public function setGenerator(DoctrineCrudGenerator $generator)
{
   $this->generator = $generator;
}
```

As you see, only the type of generator has been removed from the parameter definition and this allow me to generate my templates by using my own Generator.

Is this a bug or an enhancement which could be implemented or is there something wrong with my implementation?

Thank you for your reply

**Comment by javiereguiluz** [comment]
Closing it because I think it's "fixed" now. You can extend the `DoctrineCrudGenerator` / `DoctrineCrudGeneratorCommand` classes (or their generic `Generator` / `GeneratorCommand` equivalents) and redefine the `getGenerator()` or `setGenerator()` or `createGenerator()`.

Please, reopen this issue if you don't consider it as "fixed". Thanks!
