### ISSUE TITLE
generate:entities and traits

### ISSUE THREAD

**Issue by caramba1337** [sensiolabs/SensioGeneratorBundle#205]
Hi,

using traits in an entity and call generate:entites will always end in problems cause the generate command will create the variables and getters/setters which are defined in the trait. This causes an error define the same property ($createdAt) 

in this case i used traits for createdAt and updatedAt timestampable

Trait: https://gist.github.com/caramba1337/5927275
Entity: https://gist.github.com/caramba1337/5927268

**Comment by javiereguiluz** [comment]
Closing it because the linked Gists no longer work, so we don't have enough information to test this error. Please feel free to reopen the issue with new information. Thanks!
