### ISSUE TITLE
Generating entities with spaces in field names creates syntax errors

### ISSUE THREAD

**Issue by OskarStark** [sensiolabs/SensioGeneratorBundle#213]
This:
![bildschirmfoto 2013-07-20 um 09 37 36](https://f.cloud.github.com/assets/995707/829895/9fb7dac4-f110-11e2-998b-d6a81239280f.png)

creates this:
![bildschirmfoto 2013-07-20 um 09 36 45](https://f.cloud.github.com/assets/995707/829896/a9365184-f110-11e2-86c3-4374eac6bde9.png)

**Comment by javiereguiluz** [comment]
Closing it as "fixed" by #394.
