### ISSUE TITLE
doctrine:generate:crud with xml generates routing.yml

### ISSUE THREAD

**Issue by hdramos** [sensiolabs/SensioGeneratorBundle#225]
doctrine:generate:crud with the xml option generates 

```
Resources/config/routing.yml
```  
This happens even if Resources/config/routing.xml exists. 

Resources/config/routing/routing/entity.xml is generated properly.

Using 2.3. Bundle generated using generate:bundle with option xml.

**Comment by javiereguiluz** [comment]
I confirm this bug. Hwoever, I'm closing this issue as duplicate of #225. I know that this issue was reported earlier, but the latter includes a discussion and a linked pull request to solve the issue. Thanks.

**Comment by xabbuh** [comment]
@javiereguiluz This **is** #255. :) Which issue did you think of?

**Comment by javiereguiluz** [comment]
@xabbuh sorry! I was referring to #244.

**Comment by xabbuh** [comment]
@javiereguiluz thanks
