### ISSUE TITLE
add a flag for creating translation files

### ISSUE THREAD

**Issue by marcoalbarelli** [sensiolabs/SensioGeneratorBundle#238]
This is an enhancement request/proposal
IMHO it would be useful to create a mesages.$locale.yml file bootstrapped with properties names, for faster prototyping 

I'd be more than happy to write the code
I tried to search for something similar, but didn't find anything
Is this is useless/already implemented/already discarded for $reason ?

**Comment by OskarStark** [comment]
like your idea! :+1:

**Comment by JHGitty** [comment]
Why Yaml? The file type should be changeable. The Symfony Best Practice says XLIFF (*.xlf) should be used.http://symfony.com/doc/current/best_practices/i18n.html#translation-source-file-format
