### ISSUE TITLE
Kernel update problem when using short array syntax

### ISSUE THREAD

**Issue by lazyants** [sensiolabs/SensioGeneratorBundle#245]
generate:bundle fails when using short array syntax in AppKernel.php

```php
        if (in_array($this->getEnvironment(), ['dev', 'test'])) {
        ///...
        }
```

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because the current kernel manipulator supports both array notations. See https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Manipulator/KernelManipulator.php#L71 for details.
