### ISSUE TITLE
[Proposal] --bundle choice for doctrine:generate:crud

### ISSUE THREAD

**Issue by inmarelibero** [sensiolabs/SensioGeneratorBundle#253]
This issue is about adding a new __option__ called

    --bundle=FooBarBundle

to the 

    app/console generate:doctrine:crud

command, in order to let the user choose in which bundle he wants to put the generated code.

As is it now, the generated code is stored in the same bundle which the entity is.

#### Scenario is:
I usually put my entities in a generic bundle (eg. `Acme\SiteBundle`, meaning the _frontend bundle_ or _public bundle_), while the interfaces to manage all the entities are stored in another bundle usually called `Acme\UserBundle`, put under access control.
So when I run:

    app/console generate:doctrine:crud --entity=AcmeSiteBundle:MyEntity

I have to move the files

    src/Acme/SiteBundle/Controller/MyEntityController.php
    src/Acme/SiteBundle/Form/Type/MyEntityType.php
    src/Acme/SiteBundle/Resources/views/*

to

    src/Acme/UserBundle/
    
#### Proposal

By adding the:

    --bundle=AcmeUserBundle

I could be able to put the code in an arbitrary bundle, while keeping the entities where I prefer.

Does anyone find interesting this functionality? I looked in open and closed issues, I didn't find a similar proposal.

**Comment by javiereguiluz** [comment]
Thanks for proposing this feature. I agree with @hpatoio and I think this feature is too specific to your needs. Therefore, I'm closing it as "won't fix". We're refocusing the bundle to its core features, so adding a feaure to move the generated files (and update their namespaces, etc.) would be too much work. Thanks for understanding it.
