### ISSUE TITLE
GenerateDoctrineFormCommand not using createGenerator()

### ISSUE THREAD

**Issue by juanmf** [sensiolabs/SensioGeneratorBundle#255]
Hi, 

  I'm overriding the methd `Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineFormCommand::createGenerator()` to pass a modified DoctrineFormGenerator that unlinks the form if it already exists.

  But as the Command is not getting its DoctrineFormGenerator from the `createGenerator()` but instantiating `new DoctrineFormGenerator($this->getContainer()->get('filesystem'));` inside execute():
https://github.com/sensiolabs/SensioGeneratorBundle/blob/v2.3.4/Command/GenerateDoctrineFormCommand.php#L70
 
  So my approach is not working. 

  Shouldn't it call `protected function createGenerator()` inestead?

Thanks!
Juan

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because the latest version of this bundle correctly calls to the `createGenerator()` method through `$generator = $this->getGenerator($bundle);` instead of the direct class instantiation.
