### ISSUE TITLE
Twig_Error_Loader on bundle generation

### ISSUE THREAD

**Issue by ricfrank** [sensiolabs/SensioGeneratorBundle#258]
When i use bundle generator, after folders structure creation, i show this error log on console:

[Twig_Error_Loader]
  Unable to find template "bundle/PageController.php.twig" (looked into: /Users/riccardo/Sites/ideato/prontocalcio/vendor/sensio/generator-bundle/Sensio/Bundle/GeneratorBundle/Command/../Resources/sk
  eleton, /Users/riccardo/Sites/ideato/prontocalcio/vendor/sensio/generator-bundle/Sensio/Bundle/GeneratorBundle/Command/../Resources).

My bundle version:
"sensio/generator-bundle": "~2.3"

I use Symfony 2.4 ("symfony/symfony": "~2.4",).

The problem in solved on : "sensio/generator-bundle": "2.3.*@dev"

regards.

**Comment by MartianGreed** [comment]
Ahah, nice one dude! I was lost.... :(

**Comment by yaiceltg** [comment]
good +1
