### ISSUE TITLE
method parseShortcutNotation is wrong

### ISSUE THREAD

**Issue by garak** [sensiolabs/SensioGeneratorBundle#277]
The ``parseShortcutNotation`` method extracts entity name and bundle name just by doing a ``str_replace``. There is a wrong assumption that every entity is in the form "BundleName:EntityName", but in reality this depends on Doctrine configuration.
It should use something like ``getRepository`` method in EntityManager.

**Comment by javiereguiluz** [comment]
I'm closing this issue as "won't fix" because I think it would complicate the code just for fixing an advanced edge case. Limiting these commands to `BundleName:EntityName` syntax is a reasonable compromise to me.
