### ISSUE TITLE
Improving doctrine:generate:entity add mapping association

### ISSUE THREAD

**Issue by recchia** [sensiolabs/SensioGeneratorBundle#278]
## The Problem

The command to generate entities is very useful but when you need to map associations have to do it by hand, which is very boring and tedious

## The Solution

Add another data type called entity requesting the information for generating the association as the name of the entity with its name space and the type of relationship as a minimum. But it could also be added depending on the type of relationship more specific attributes.

For example:

type field: entity
type of relation: manytoone

optional:

mappingby
inversedby
joincolumn
jointable

as appropriate

PD: Please put DX label

**Comment by zeopix** [comment]
https://github.com/sensiolabs/SensioGeneratorBundle/pull/352

**Comment by javiereguiluz** [comment]
Recently we decided to refocus the purpose of this bundle and work only on its core features. Supporting entity associations is one of the features that we prefer to not implement yet. The alternative solution is to use third-party bundles such as SonataAdmin, which support this and many other complex features.

Therefore, I'm closing this and all the other related issues and pull requests as "won't fix". Thanks for understanding it.
