### ISSUE TITLE
[generate:doctrine:entity] Default to current bundle metadata definition format

### ISSUE THREAD

**Issue by lmcd** [sensiolabs/SensioGeneratorBundle#28]
The Symfony2 documentation states:
"A bundle can accept only one metadata definition format. For example, it's not possible to mix YAML metadata definitions with annotated PHP entity class definitions."

If someone is using YAML metadata definitions throughout their project, the generator should detect this and use it as the default. Also, if the user decides to generate annotated mapping information (for example) when YAML is used elsewhere, an error/warning should be produced.

**Comment by phansys** [comment]
I think this old issue is **actionable** at least if the [type](http://symfony.com/doc/current/reference/configuration/doctrine.html#type) mapping is specified for the bundle NS.

**Comment by javiereguiluz** [comment]
@phansys could you estimate the amount of code needed to implement this feature? I think we should close this issue as "won't fix" if it requires a lot of changes. Thanks!

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
