### ISSUE TITLE
[DX] generate:crud Minor Suggested Improvements

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioGeneratorBundle#283]
Hi there!

Apologies, as I'm sure some of these will be duplicates of existing issues. It doesn't seem like this library gets a lot of love, but I think we can change that. There is a *lot* we can do with this bundle, and it will probably include the ability to generate CRUD's for different circumstances, etc.

Here are a few quick items:

* [x] A) Rename `$entity` to something real - like `$product` or `$blogPost` for a `BlogPost` entity

* [ ] B) Extend a base template in the generated templates. It's ok if we need to ask this user which one

* [ ] C) Use the same method for new/create and edit/update

**Comment by javiereguiluz** [comment]
Closing it as fixed because the big #377 PR includes several of the features asked for in this issue. Thanks!
