### ISSUE TITLE
[DX] Potential missing annotation route import

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioGeneratorBundle#284]
I _believe_ there is a bug when using `doctrine:generate:crud` with the annotation format. Specifically, the routing import (to import the `Controller` directory with `type: annotation`) is not added. I believe you can see this here: https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Command/GenerateDoctrineCrudCommand.php#L122

My guess is that the thought is that if you originally generated the bundle with the annotation config format, then you'll already have this import. We should do a little more work to make sure that the controller _is_ in fact being imported in routing. Without it, the CRUD seems to not work at first.

Thanks!

**Comment by HeahDude** [comment]
I'm closing here since I've opened #527 to fix the controller generator command and the CRUD one was already fixed in #403. Thanks!
