### ISSUE TITLE
[DX] Re-work generate:bundle for simple app bundles

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioGeneratorBundle#290]
Relates to symfony/symfony-docs#3964 and #67 

There should really be 2 modes for the bundle generation:

1) Creating a re-usable, 3rd party bundle
2) Creating a bundle for your application

Perhaps we ask this question first then:

>
Are you planning on using/sharing this bundle across multiple applications?

Regardless, the vendor namespace should be optional. And really, it should *not* be recommended (if we ask the above question, we could still recommend it if you *are* building a re-usable bundle).

Also, if you're building a bundle for your application, no `DependencyInjection` directory should be created.

**Comment by javiereguiluz** [comment]
This issue can be closed because #312 was already merged.
