### ISSUE TITLE
Impossible to generate CRUD for entities inherited

### ISSUE THREAD

**Issue by maidmaid** [sensiolabs/SensioGeneratorBundle#297]
If I have an entity class Cheese that inherits of entity Products, the CRUD Command does not take into account fields of Products. Metadata used doesn't load the informations of super class. The metadata factory used is ```DisconnectedMetadataFactory``` (in ```GenerateDoctrineCommand::getEntityMetadata()```). If I replace it with ```\Doctrine\Bundle\DoctrineBundle\Mapping\MetadataFactory```, it works.

**Comment by javiereguiluz** [comment]
I'm closing this issue as "won't fix" because we are rethinking the purpose of this bundle to not complicate it too much. Entity inheritance is one of the edge features that we've decided to not support for now. Thanks for understanding it.
