### ISSUE TITLE
Switch to event-backed generators

### ISSUE THREAD

**Issue by kix** [sensiolabs/SensioGeneratorBundle#324]
Follow-up to [symfony/symfony#12943](https://github.com/symfony/symfony/issues/12943)

For example, let's take a look at how controllers are currently generated:
- I call `app/console generate:controller`, interact with it
- the `ControllerGenerator` renders scaffolds for my controller and its views from templates supplied
- depending on if and which routing type I choose, my `routing.(yml|xml)` is updated with values matching  my controller setup

This is not so flexible:
- If my whole project uses `phpspec` instead of default PHPUnit, I'd anyway get a test generated. 
- If I've switched to HAML templates (using [`MtHamlBundle`](https://github.com/arnaud-lb/MtHamlBundle) or whatnot), I'd get `.html.twig` or `.php.twig` templates anyway

...etc, etc. The main point is that all the generators are hard-coded into the `ControllerGenerator`. What I suggest to implement:
- make sure generator commands always have an event dispatcher,
- once a generator command has succeeded, it should trigger a subclassed event that includes some data about the run and its results,
- the console application has a mechanism to hook on console command events beyond the standard `COMMAND`, `TERMINATE` and `EXCEPTION` set,
- if there's a listener matching the event, it gets called (that's just normal Sf2 event flow),
- the listener calls generators, validators, etc.

This way, when I was to generate a controller, the generator itself would just generate the controller class, then it'd trigger a `ControllerCreated` console event, which would then be caught by (to be implemented):
- a `ControllerViewGeneratorListener` from `TwigBundle` to generate my Twig files, 
- a `ControllerTestGeneratorListener` from, IDK, `FrameworkBundle`, to generate tests for my new controller,
- a `RouteUpdaterListener` to update my routing files.

Having such mechanism for hooking on generator events, we could allow third-party bundles to add their own hooks and listeners for this mechanism, so that `MtHamlBundle` would build `haml` views for a new controller, a `PHPSpecBundle` (no such thing yet?) would generate specs, etc.

**Comment by fabpot** [comment]
Looks very interesting to me.

**Comment by JHGitty** [comment]
Sounds interesting. :+1:

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
