### ISSUE TITLE
CRUD generator does not update router.php

### ISSUE THREAD

**Issue by nimasdj** [sensiolabs/SensioGeneratorBundle#327]
Here I discovered a bug:
http://community.sitepoint.com/t/a-possible-bug-in-sensiobundlegenerator/109480/2

**Comment by javiereguiluz** [comment]
I'm closing it because the error report is not clear. Please, add all the information about the error in this GitHub issue, not in a external user support forum. Thanks.

**Comment by xabbuh** [comment]
maybe the same as #225
