### ISSUE TITLE
is_bundle false has problems in CRUD class

### ISSUE THREAD

**Issue by nimasdj** [sensiolabs/SensioGeneratorBundle#329]
SensioGenerator for CRUD class still needs to be more clever when is_bundle is false.
when is_bundle is fals it still use:
```
    public function createAction(Request $request)
    {
        $entity = new Admin();
```
and:

```
    private function createCreateForm(Admin $entity)
    {
```
and this in data_class:

```
        $resolver->setDefaults(array(
            'data_class' => 'Application\Bundle\Admin'
        ));
```

But instead should be something like:

```
    public function createAction(Request $request)
    {
        $entity = new \Entities\Admin();
```
```
    private function createCreateForm(\Entities\Admin $entity)
    {
```

and this in data_class:
```
        $resolver->setDefaults(array(
            'data_class' => 'Entities\Admin'
        ));
```

**Comment by nimasdj** [comment]
or at least this is better it adds use statement automatically:
```php
use Entities\Admin;
```

**Comment by javiereguiluz** [comment]
@nimasdj thanks for reporting this issue. We're going to try fixing it, but I'm closing this issue as duplicated of #335 (your issue is older, but the other one includes more information).
