### ISSUE TITLE
DoctrineCrudGenerator Always Overwrites Controller Bug + Solution

### ISSUE THREAD

**Issue by mogilvie** [sensiolabs/SensioGeneratorBundle#331]
When executing the  command 

```    
php app/console generate:doctrine:crud
```
The generator overwrites existing controllers even when --overwrite is false.

Cause of the problem appears to be in the DoctrineCrudGenerator class where the check on force overwrite looks at $target.

Sprintf format has an extra forward slash resulting in invalid file path.

Fix is to replace
%s/Controller/%s/%sController.php
with 
%s/Controller%s/%sController.php
Full function below.

    protected function generateControllerClass($forceOverwrite)
    {
        $dir = $this->bundle->getPath();

        $parts = explode('\\', $this->entity);
        $entityClass = array_pop($parts);
        $entityNamespace = implode('\\', $parts);

        $target = sprintf(
            '%s/Controller%s/%sController.php',
            // Modified due to error returning double // and market target invalid
            // $dir
            substr($dir, 0 ,-1),
            str_replace('\\', '/', $entityNamespace),
            $entityClass
        );

        if (!$forceOverwrite && file_exists($target)) {
            echo "fired";
            throw new \RuntimeException('Unable to generate the controller as it already exists.');
        }

        $this->renderFile('crud/controller.php.twig', $target, array(
            'actions'           => $this->actions,
            'route_prefix'      => $this->routePrefix,
            'route_name_prefix' => $this->routeNamePrefix,
            'bundle'            => $this->bundle->getName(),
            'entity'            => $this->entity,
            'entity_class'      => $entityClass,
            'namespace'         => $this->bundle->getNamespace(),
            'entity_namespace'  => $entityNamespace,
            'format'            => $this->format,
        ));
    }
'''

**Comment by javiereguiluz** [comment]
I'm closing this issue as "fixed". I've just tested it.

When executing `doctrine:generate:crud`, the existing controller isn't overridden:

![ovewrite_controller](https://cloud.githubusercontent.com/assets/73419/8751518/d7e77dfc-2cad-11e5-8c02-4a48322a7460.png)

When executing `doctrine:generate:crud --overwrite`, the existing controller is correctly overridden:

![ovewrite_controller_ok](https://cloud.githubusercontent.com/assets/73419/8751592/56af7d60-2cae-11e5-9e84-83afe1c6ed8e.png)

**Comment by developpeurk** [comment]
thanks
