### ISSUE TITLE
[Proposal] Generate a command class quickly !

### ISSUE THREAD

**Issue by sheikhu** [sensiolabs/SensioGeneratorBundle#332]
Hi all ! 

What do you think about a command to quickly generate a command class ? 
If we have to create a command line app , it's annoying to manually create each time a class for a command.

I propose something like `generate:command --command=AppBundle:Acme`. This will result in the creation of a class named `AcmeCommand` in `Command/` folder inside `AppBundle`.

Please let me know what do you think !

**Comment by JHGitty** [comment]
+1 :+1: 
If there is a generator for entities and other things there should also be a generator for commands.

**Comment by ConneXNL** [comment]
+1
