### ISSUE TITLE
Uses of the depreacted setDefaultOptions

### ISSUE THREAD

**Issue by theofidry** [sensiolabs/SensioGeneratorBundle#336]
When we generate a form via the crud command php app/console doctrine:generate:crud, in the form type generated, we get the deprecated method of public function setDefaultOptions(OptionsResolverInterface $resolver) instead of public function configureOptions(OptionsResolver $resolver).

Symfony version: 2.6.4.

**Comment by xabbuh** [comment]
This cannot be changed for Symfony 2.6 since `configureOptions()` will only be part of Symfony 2.7.

**Comment by theofidry** [comment]
oh... Sorry I though it worked well on Sf2.6 :(
