### ISSUE TITLE
Customizable views for generators.

### ISSUE THREAD

**Issue by aybarscengaver** [sensiolabs/SensioGeneratorBundle#337]
Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator::generateIndexView
Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator::generateShowView
Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator::generateNewView
Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator::generateEditView

I think, this methods should be  customizable for twig files.

**Comment by xabbuh** [comment]
@aybarscengaver Customizing the template files is not sufficient?

**Comment by aybarscengaver** [comment]
For example, i want to change crud twig and controller files like https://github.com/okulbilisim/ojs/blob/master/src/Ojs/JournalBundle/Controller/ArticleController.php#L48  

But i must change files after running crud generator.

Or :

If i want to make grid supported list views like https://github.com/okulbilisim/ojs/blob/master/src/Ojs/JournalBundle/Resources/views/Article/index.html.twig#L20
, i must recode every list pages.

That's not useful.
