### ISSUE TITLE
Controller generator doesn't work with the latest best practices

### ISSUE THREAD

**Issue by parhamdoustdar** [sensiolabs/SensioGeneratorBundle#339]
In the best practices document, it's said that:

> Store all your application's templates in app/Resources/views/ directory.

However, the generator seems to infer that I want to share my bundle and put the template in the `Resources/views/` directory of the `AppBundle` bundle.

**Comment by JHGitty** [comment]
+1 :+1: 
Relates to https://github.com/sensiolabs/SensioGeneratorBundle/issues/344

**Comment by fabpot** [comment]
closing as a duplicate of #344

**Comment by jasonroman** [comment]
I don't think this issue should be closed.  The current controller generator does not use the Doctrine CRUD Generator to determine template names, and still requires double-colons and still places templates inside the bundle directory, rather than app/Resources/views
