### ISSUE TITLE
The crud-generator doesn't follow symfony best practices

### ISSUE THREAD

**Issue by emil-nasso** [sensiolabs/SensioGeneratorBundle#344]
Are there any plans to change the generator so that it follows the best practices available at http://symfony.com/doc/current/best_practices/index.html ?

To my understanding a new demo application will be released with symfony 2.7.  ( http://symfony.com/blog/introducing-the-symfony-demo-application)

The demo application follows the best practices recommendations, it would be really nice if the generator would too.

As a know symfony developer i started out by reading the book and then the best practices document and experimented a bit with it. I felt like i had a good idea on how to write symfony applications. Then i used the crud-generator and had a "what the hell"-moment. ;)

**Comment by JHGitty** [comment]
+1 :+1: 
I was going to create the same issue today and found this issue.

```
Don't use the @Template() annotation to configure the template used by the controller.
```
http://symfony.com/doc/master/best_practices/controllers.html#template-configuration

**Comment by emil-nasso** [comment]
I think the largest issue is that it uses three methods for each action. For creating an entity, there is `createCreateForm`, `createAction` and `newAction`. The best practices does this with one method in a much less verbose and clean way. This takes a bit of work to refactor so i usually just write everything myself, from scratch.

**Comment by JHGitty** [comment]
@emil-nasso same here!

**Comment by Lewik** [comment]
@emil-nasso +1

**Comment by maidmaid** [comment]
Here are my suggestions for improvements:

1) [So it's much simpler to let newAction handle everything.](http://symfony.com/doc/current/best_practices/forms.html#handling-form-submits)

While with current generator :

```php
public function createAction(Request $request) {}
public function newAction() {}
```

2) [Add buttons in the templates, not in the form classes or the controllers.](http://symfony.com/doc/current/best_practices/forms.html#form-button-configuration)

While with current generator :

```php
$form->add('submit', 'submit', array('label' => 'Create'));
```

3) [Store all your application's templates in app/Resources/views/ directory](http://symfony.com/doc/current/best_practices/templates.html#template-locations)

While with current generator, templates is stored in AppBundle/Resources/views/

4) [Rendering the Form](http://symfony.com/doc/current/best_practices/forms.html#rendering-the-form)

```twig
{{ form_start(form, {'attr': {'class': 'my-form-class'} }) }}
    {{ form_widget(form) }}
{{ form_end(form) }}
```

While with current generator :

```twig
{{ form(edit_form) }}
```

5) [Don't use the @Template() annotation to configure the template used by the controller.](http://symfony.com/doc/current/best_practices/controllers.html#template-configuration)

While with current generator :

```php
/**
  * Lists all Category entities.
  *
  * @Route("/", name="category")
  * @Method("GET")
  * @Template()
  */
 public function indexAction() {}
```

6) [Second, we recommend using $form->isSubmitted() in the if statement for clarity. ](http://symfony.com/doc/current/best_practices/forms.html#handling-form-submits)

While with current generator :

```php
if ($form->isValid()) {}
```

7) Names variables are very generic, it use ``$entity`` and ``$entities`` :

```php
$entity = new Category(); // in newAction
$entities = $em->getRepository('AppBundle:Category')->findAll(); // in indexAction
```

It would be better with a more contextuel name :

```php
$category = new Category(); // in newAction
$categories = $em->getRepository('AppBundle:Category')->findAll(); // in indexAction
```

I think for it, an plurialized filter twig would be needed as exception for categor**y** -> categor**ies**.

8) [Use the ParamConverter trick to automatically query for Doctrine entities when it's simple and convenient](http://symfony.com/doc/current/best_practices/controllers.html#using-the-paramconverter)

While with current generator :

```php
public function showAction($id)
{
    $em = $this->getDoctrine()->getManager();
    $entity = $em->getRepository('AppBundle:Category')->find($id);
    //...
}
```

9) Current generator doesn't use ``redirectToRoute()`` shortcut notation for routage :

```php
return $this->redirect($this->generateUrl('category'));
```

10) Current generator doesn't use ``requirements`` in routes definitions :

```php
/**
 * Finds and displays a Category entity.
 *
 * @Route("/{id}", name="category_show")
 * @Method({"GET", "POST"})
 */
public function showAction($id) {}
```

In this case, add ``requirements={"id" = "\d+"}`` would be better.

11) [Use lowercased snake_case for directory and template names.](http://symfony.com/doc/current/best_practices/templates.html#template-locations)

While with current generator : ``AppBundle:Category:index.html.twig``

**Comment by fabpot** [comment]
Anyone willing to make the needed changes?

**Comment by maidmaid** [comment]
Yes, I can take care of this.

**Comment by fabpot** [comment]
@maidmaid Thank you so much.
