### ISSUE TITLE
Better look and feel for the generated crud tables?

### ISSUE THREAD

**Issue by mfivebusiness** [sensiolabs/SensioGeneratorBundle#354]
Hi there,

Thanks for your contribution in this repo. I just followed the instructions provided here: http://symfony.com/doc/current/bundles/SensioGeneratorBundle/commands/generate_doctrine_crud.html
Now, I could generate crud forms and view for my entities. There are also some styling classes (e.g., recorde_action) are used in the generated twig files. However, I couldn't find where those css classes are defined. I wonder if you can help me find such classes.

Thanks.

**Comment by javiereguiluz** [comment]
If your question is about where those CSS classes are created, the answer is in the templates defined by the "skeleton" and which are used to generate the definitive templates of the CRUD. You can see those templates here: https://github.com/sensiolabs/SensioGeneratorBundle/tree/master/Resources/skeleton/crud/views

If your question is where are those CSS classes used to stylize elements, the answer is none :)  This bundle is just to bootstrap your CRUD, so no styles are applied or provided.

**Comment by mfivebusiness** [comment]
Thanks for your detailed explanation. It's already solved.
