### ISSUE TITLE
yaml config controllers not listed under debug:router command

### ISSUE THREAD

**Issue by laurencefass** [sensiolabs/SensioGeneratorBundle#356]
ive created two controllers with "php app/console generate:controller"

controllers created with [default] annotation config are listed under command "app/console debug:router"

controllers created selecting yaml config are not listed under command "debug:router".

brand new install of symfony and this is the first thing ive tried. any idea whats gone wrong?

**Comment by xabbuh** [comment]
Please use the mailing list or IRC for support questions.
