### ISSUE TITLE
generate:bundle --shared Option does not exist

### ISSUE THREAD

**Issue by JarJak** [sensiolabs/SensioGeneratorBundle#358]
Please update the docs:

https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Resources/doc/commands/generate_bundle.rst

 Is ```--shared``` option same as ```--structure``` ?

**Comment by phansys** [comment]
I don't think so @JarJak. See #312 (in which `shared` option was introduced).
Which version of this bundle are you using? Please, be sure you're reading the docs for the version you use.

**Comment by javiereguiluz** [comment]
As explained by @phansys, the `--shared` option was introduced recently and that's why it's only documented in the most recent version of the bundle. That's why I'm closing this issue as fixed. If you don't agree, please reopen the issue. Thanks.
