### ISSUE TITLE
Remove unused variables from generated Config/Extension classes

### ISSUE THREAD

**Issue by adamquaile** [sensiolabs/SensioGeneratorBundle#363]
`$rootNode` and `$config` are unused in the generated code: 

```
public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('{{ extension_alias }}');

        // Here you should define the parameters that are allowed to
        // configure your bundle. See the documentation linked above for
        // more information on that topic.

        return $treeBuilder;
    }
```

and 

```
public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        //...
    }
```

Personally, I remove them until I actually need them, and I know some CI tools warn about unused variables, depending on how they're configured. 

Are they just there as prompts for those wanting to configure their bundles further? Can we remove them from the template?

**Comment by fabpot** [comment]
There are there as reminder. Feel free to remove them if you don't need them, but we need to keep them.
