### ISSUE TITLE
[doc] Documentation version wrongly exposed in symfony.com

### ISSUE THREAD

**Issue by phansys** [sensiolabs/SensioGeneratorBundle#371]
**https://symfony.com/doc/master/bundles/SensioGeneratorBundle/index.html** shows ```2.4 version``` in dropdown but URI and contents points to master version of docs.
I don't know if this can be solved in [symfony/symfony-marketing](https://github.com/symfony/symfony-marketing).

![image](https://cloud.githubusercontent.com/assets/1231441/8490586/c7a9ad6e-2101-11e5-9a0c-aadb639c9659.png)

**Comment by fabpot** [comment]
Indeed, I've fixed that and it will be fixed online after the next deploy. Thanks for noticing.
