### ISSUE TITLE
[RFC] Discourage the use of "/" as NS separator in shortcut notations

### ISSUE THREAD

**Issue by phansys** [sensiolabs/SensioGeneratorBundle#373]
I think it should be better to always use the default NS separator ("\").
If this RFC is approved, all tests, docs, exception messages should use it:

**Before**:
```
AcmeBlogBundle:Blog/Post
```

**After**:
```
AcmeBlogBundle:Blog\Post
```

**Comment by fabpot** [comment]
I don't think so. Using a blackslash on a console for instance can give you surprising results depending on the next character.

**Comment by phansys** [comment]
Good point. Can we normalize the usage for just `/` then adding some notes about the reason for this?
Take [this misuse](https://github.com/symfony/symfony/issues/3019#issue-2707740) as example.

**Comment by javiereguiluz** [comment]
@phansys I'd like to fix or close this issue. Could you please tell me more specifically the changes that you propose to tackle this? Thanks!

**Comment by javiereguiluz** [comment]
Closing it as "not actionable". Feel free to reopen it and provide more feedback. Thanks!
