### ISSUE TITLE
[RFC] Document branching strategy

### ISSUE THREAD

**Issue by phansys** [sensiolabs/SensioGeneratorBundle#375]
It would be nice to have a documented branching strategy in order to know against which branch submit patches or features, in the same way that this is exposed for [symfony](http://symfony.com/doc/current/contributing/code/patches.html#choose-the-right-branch).

**Comment by javiereguiluz** [comment]
Closing it because none of the first-party Symfony bundles document their branch strategy. I'd say that it's safe to keep assuming that all pull requests must be created against the `master` branch.
