### ISSUE TITLE
[Doc] "versionadded" wrongly parsed in symfony.com

### ISSUE THREAD

**Issue by phansys** [sensiolabs/SensioGeneratorBundle#376]
[```versionadded:: 3.0```](https://github.com/sensiolabs/SensioGeneratorBundle/commit/8ebcfb8a874ef0c5c00758a90bec8218038793a2#diff-e633290f64d9b2641b597a0d26be7e62R42) is shown as 2.8 in [symfony.com](https://symfony.com/doc/master/bundles/SensioGeneratorBundle/commands/generate_doctrine_entity.html#available-options):

![image](https://cloud.githubusercontent.com/assets/1231441/8526828/5d065d46-23df-11e5-929f-20c74cb8ef40.png)

**Comment by javiereguiluz** [comment]
@phansys thanks for reporting this error. It's already been fixed and it will be available on production once the website is deployed. Thanks!
