### ISSUE TITLE
Add table name to ORM definition by default

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [sensiolabs/SensioGeneratorBundle#378]
I came across the following problem a few times. It is based on how different systems handle uppercase/lowercase.

Using the generator `php app/console generate:doctrine:entity` I created an entity named `Foo` (uppercase) on my local windows system. I ended up with a table named `foo` (lowercase) in my database. I committed the code to my repository and pulled the change on a linux server. On the server I executed my code to generate the entity, and I ended up with a table named `Foo` (uppercase).

I don’t know where exactly the difference in upper/lower case comes from, but an easy fix for me was to define the table name in the ORM for the entity:

```php
// AcmeBundle/Entity/Foo.php

/**
 * Foo
 *
 * @ORM\Table(name="foo")
 * @ORM\Entity(repositoryClass="AcmeBundle\Entity\FooRepository")
 */
```
This code generates the exactly same table name (lowercase `foo`) on both systems.

For me it would be beneficial if the generator would specify the table name every time I create a new entity. 

Are there any possible drawbacks to this?

**Comment by javiereguiluz** [comment]
@centigrade-thomas-becker thanks for proposing this improvement. I like the idea and I think we can easily implement it thanks to the `Doctrine\Common\Util\Inflector::tableize()` method. Can anyone think of any issue for implementing this feature?

**Comment by centigrade-thomas-becker** [comment]
Much appreciated
