### ISSUE TITLE
[RFC] Rethink the scope of this bundle

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#382]
### Problem

This bundle was originally created to help you bootstrap your bundles/entities/CRUD/etc. The code generated is just a starting point, not the final result that your application expects.

Take for example the CRUD generator: there are a lot of requests to support features such as entity relations. In my opinion that's not necessary. If you need to create a complex backend, you should use SonataAdmin instead of this bundle.

### Solution

I propose to close the following issues and pull requests as *won't fix* and get this bundle back to its original purpose:

* CRUD Generator and joined entities #81
* Support of relations in the entity generator command #152
* Doctrine Crud generation of many entities at once #168
* Improving doctrine:generate:entity add mapping association #278
* Added relations support to entity mapping generator #352
* Is it possible to create a new directory via crude command? #311
* Impossible to generate CRUD for entities inherited #297
* [console] Fix inheritance bundle selection in controller generation
* Is there a way to generate forms from entities declared outside of a bundle ? #323
* [DX] Display the list of available entities #293
* [DX] Improving generate:doctrine:crud #293 #300
* Adding Autocomplete of Entity shortcut names to doctrine:generate:crud Command #246
* Added support for entity name autocompletion in the CRUD generator. #288
* [DX] Generate DependencyInjection #308
* Proposal - Multiple skeleton choise #265
* Introduced automatically adding a twig extends tag and blockname #109
* Support for adding enabling multiple bundles via KernelManipulator #260
* [GenerateDoctrineEntityCommand] Added option to set id generator strategy #362

**Comment by fabpot** [comment]
I totally agree with you. I've just made you an admin of this repo so that you can cleanup things yourself. Thanks.

**Comment by phansys** [comment]
I agree with this but at first, only in cases where the generated code is extensible with just additions (no removals or replacements). By instance, the type for `Id` property, which is always ```integer``` leaves off the chance to choose another generation strategy.

**Comment by javiereguiluz** [comment]
Closing it because the new scope of the bundle has been approved. Thanks!

**Comment by zeopix** [comment]
I'm totally agree with the basic understanding of the scope of this bundle. 
> (...) to help you bootstrap your bundles/entities/CRUD/etc (...) is just a starting point (...)

But I don't think the most of the features you mentioned, they are intended to be used to produce 'final code'.
I think most of them are features which could help to bootstrap new code even faster than now, it's not a matter of generating more 'complex' and 'smart' or 'final' code, it's a matter of improving the tools with really soft additions that can make difference. 

Anyway, thanks a lot for all your contributions, and all my respects in your decisions.
Symfony project is just awesome!

**Comment by javiereguiluz** [comment]
@zeopix recently we applied a strict policy to close and reject most feature requests. This was needed to "regain the control" of the bundle. Once we stabilize the backlog, we'll be allowed to think about new features again. Thanks for understanding it.
