### ISSUE TITLE
Doc in IT?

### ISSUE THREAD

**Issue by JellyBellyDev** [sensiolabs/SensioGeneratorBundle#399]
Hi,
where is the documentation in Italian languages for this bundle that i see here: http://symfony.com/it/doc/current/bundles/SensioGeneratorBundle/commands/generate_bundle.html
I can not find the source in this bundle!
Thanks

**Comment by javiereguiluz** [comment]
The italian docs are available in a separate repository: https://github.com/garak/symfony-docs-it

**Comment by JellyBellyDev** [comment]
I tried, but there are no translations of the bundle!

**Comment by fabpot** [comment]
Closing as we don't provide/include translations for bundles.
