### ISSUE TITLE
Is this file from the bundle skeleton still used?

### ISSUE THREAD

**Issue by OskarStark** [sensiolabs/SensioGeneratorBundle#404]
SensioGeneratorBundle/Resources/skeleton/bundle/```messages.fr.xlf``` ?

**Comment by javiereguiluz** [comment]
It was used in the past when generating the bundle with the "extended file structure" option set. Now we only use the `shared` option, which controls whether the `DependencyInjection/` directory is generated or not. I assume it's safe to remove this file.
