### ISSUE TITLE
Can you please create a new 2.5 release?

### ISSUE THREAD

**Issue by OskarStark** [sensiolabs/SensioGeneratorBundle#405]
so we can get this commit: https://github.com/sensiolabs/SensioGeneratorBundle/commit/a59ec8bf98a80fa9a8a516a1b6c724273afee846#diff-f9d28005649d357bd4ce4a7bdf316f00

after this the line is shorter than 120 characters, that means, that the generated bundle has valid CS

thank you

**Comment by javiereguiluz** [comment]
Closing it because a new version will be released soon, but we don't follow a strict schedule as Symfony does.
