### ISSUE TITLE
Error generating a Bundle

### ISSUE THREAD

**Issue by tsantos84** [sensiolabs/SensioGeneratorBundle#417]
I'm trying to generate a Bundle using SensioGeneratorBundle but the bellow error is throw when runing the command:

    Unknown tag name "raw" in "bundle/index.html.twig.twig" at line 1

**Comment by xabbuh** [comment]
Which version of the bundle do you use?

**Comment by tsantos84** [comment]
Hi, sorry for long time without reply you. But the version is the last one (v2.5.3)

**Comment by xabbuh** [comment]
0dad775dff1fd4374565a4752b33ed937383dd8d which changed the template was committed in July so you will probably have to switch to the latest development version until the next release is published.

**Comment by HeahDude** [comment]
Hi @tsantos84, the only maintained version today is 3.0.

I'm closing as your issue should be fixed, feel free to reopen if you still encounter this problem.

Thanks
