### ISSUE TITLE
Available versions

### ISSUE THREAD

**Issue by heitorvrb** [sensiolabs/SensioGeneratorBundle#419]
I've been following the development of this bundle, specially feature #377. I see it has been merged in the `master` branch, but it isn't available in the `2.5` branch.

I'm new to composer, and using Symfony 2.7.5, which version of this bundle should I use? `composer show` shows me versions `dev-master`, `3.0.x-dev`, `2.5.x-dev` and `v2.5.3`

**Comment by fabpot** [comment]
If you want #377, your need `3.0.x-dev`.
