### ISSUE TITLE
Add fields variable to crud generator ( new )

### ISSUE THREAD

**Issue by Micchaleq** [sensiolabs/SensioGeneratorBundle#420]
Hi masters :)

I have request for you. 
I created my own generate theme but all the time if i install new project I have to edit your controller.
I need a 'fields' return from generateNewView in DoctrineCrudGenerator.

Any other methods ( index, edit, show ) have it but not new.

**Comment by JHGitty** [comment]
As I understand you may use a customized skeleton template:
http://symfony.com/doc/current/bundles/SensioGeneratorBundle/index.html#overriding-skeleton-templates

**Comment by JHGitty** [comment]
There is already a 'fields' entry in the array?
https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Generator/DoctrineCrudGenerator.php#L266

**Comment by javiereguiluz** [comment]
Closing it as fixed because the `fields` variable was added to `generateNewView()` in August 2015: https://github.com/sensiolabs/SensioGeneratorBundle/commit/f2b202a7c3e5f2850abf51776c6b8d91dc675b08
