### ISSUE TITLE
[CRUD] deprecated method: FormTypeInterface::setDefaultOptions()

### ISSUE THREAD

**Issue by zatikbalazs** [sensiolabs/SensioGeneratorBundle#423]
I ran ``generate:doctrine:crud`` in a Symfony 2.7.5 application and the profiler gave me the following warning when I accessed one of the generated files:

> DEPRECATED - AppBundle\Form\UserType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead.

Is SensioGeneratorBundle still using ``FormTypeInterface::setDefaultOptions()`` because of backwards compatibility?

**Comment by xabbuh** [comment]
You could upgrade to the latest dev version of the bundle which contains a fix for your issue.

**Comment by zatikbalazs** [comment]
Thank you. I hope the next stable version will be released soon with all the fixes.
