### ISSUE TITLE
Sensio\Bundle\GeneratorBundle\Generator $skeletonDirs variable access to extend it to add translate filter to twig instance

### ISSUE THREAD

**Issue by userlond** [sensiolabs/SensioGeneratorBundle#424]
Hi, I'am a novice to symfony (and oop :) ), so don't judge strictly.

I need to add | trans filter to twig templates of Symfony SE crud generator. But generator instantiates its own Twig instance (entirely independent of Symfony), so there is not translation.

Idea is to extend it with my own generator which  adds translate extension to twig instance. Method getTwigEnvironment() has protected access, but $skeletonDirs has private access and no getter, so I can't get it from my child class.

So I suggest to add getter for $skeletonDirs or make it protected.

P.S. Maybe, anybody knows true way to translate crud :)

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
