### ISSUE TITLE
Doctrine CRUD, Create action not working

### ISSUE THREAD

**Issue by khalid-s** [sensiolabs/SensioGeneratorBundle#448]
When doing a CRUD, with sf3, the /new route is generating this error:
```
Expected argument of type "string", "sf\SfBundle\Form\TestType" given
```
Error is comming from here : in 
```
vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 64
```

**Comment by xabbuh** [comment]
see #435 and #436

**Comment by khalid-s** [comment]
@xabbuh it does not seem to be the same problem

**Comment by xabbuh** [comment]
@khalid-s Why do you think so?

**Comment by khalid-s** [comment]
Because i tested on a fresh sf3 install the sension generator bundle on both the dev-master and the 3.0.1 version and still having the same error.

it bugs at the createForm() in the new action before even trying to generate a view.

**Comment by xabbuh** [comment]
Well, the pull requests are not merged yet.

**Comment by FabienPapet** [comment]
Actually, it is the same problem as  #435 , as the first argument of `createForm` must be a string instead of an `AbstractType` instance.

**Comment by matudelatower** [comment]
In "sensio/generator-bundle": "~3.0"

throws

<img width="896" alt="captura de pantalla 2015-12-18 a las 11 05 53 a m" src="https://cloud.githubusercontent.com/assets/5694115/11898606/be28bf96-a577-11e5-8a28-50dbdf573dd3.png">

The field in mi entity.
```
    /**
     * @var integer $creadoPor
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="UsuariosBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="creado_por", referencedColumnName="id", nullable=true)
     */
    private $creadoPor;
```
