### ISSUE TITLE
2.3 put the twig file in src dir but 3.0 in app?

### ISSUE THREAD

**Issue by xxfaxy** [sensiolabs/SensioGeneratorBundle#466]
It's a bug?

**Comment by xabbuh** [comment]
Generating templates in the `app/Resources/views` directory was done to follow the [best practices](http://symfony.com/doc/current/best_practices/templates.html#template-locations).

**Comment by javiereguiluz** [comment]
@xxfaxy thanks for reporting this change. However, as @xabbuh said, this is intended a not a bug, so I'm closing this issue.
