### ISSUE TITLE
Repository class written in the wrong location

### ISSUE THREAD

**Issue by robinkanters** [sensiolabs/SensioGeneratorBundle#469]
_Disclaimer: So I think I've seen a similar issue before, but I couldn't find it._

When I just used 'doctrine:generate:entity' for a new entity, this was the output:

```
> Generating entity class /home/robin/Projects/xyz-bundle/Entity/CustomerOrder.php: OK!
> Generating repository class /home/robin/MyCompany/XyzBundle/Repository/CustomerOrderRepository.php: OK!
> Generating mapping file /home/robin/Projects/xyz-bundle/Resources/config/doctrine/CustomerOrder.orm.yml: OK!
```
Notice that it put the repository class way outside of the project. I did some investigation and found [this line of code](https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Generator/DoctrineEntityGenerator.php#L107). Since my bundle namespace is `MyCompany\XyzBundle\`, it places two `../`'s, ending up outside my project. To me, it seems that `$bundle->getPath()` should already return the root of the bundle, so shouldn't this always be a problem? Also, why is this code only used for the repository class path?

Strangely, that line has been in the code for almost a year. Also, when I changed it to `$path = $bundle->getPath()`, it fixed my issue.

Is this a bug, and if so, should this be fixed? Are other people running into this?

**Comment by HeahDude** [comment]
Hi @robinkanters what version are you using?

**Comment by robinkanters** [comment]
If you'd have asked me 8 months ago, I'd have known, now I don't remember
