### ISSUE TITLE
[CRUD] 500 error when creating new entry if entity name is CamelCase 

### ISSUE THREAD

**Issue by PapyDanone** [sensiolabs/SensioGeneratorBundle#472]
I get the following error in `src/AppBundle/Controller/CamelCaseController.php`:

    Undefined variable: camelcase

![screen shot 2016-02-11 at 11 36 37 am](https://cloud.githubusercontent.com/assets/804367/12982667/c6a943c2-d0b3-11e5-9874-15e1935d69d9.png)

It seems like the controller skeleton file shouldn't be using `${{ entity_class|lower }}` [here](https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Resources/skeleton/crud/actions/new.php.twig#L29).

It works fine in the `edit` view.

**Comment by xabbuh** [comment]
see #450
