### ISSUE TITLE
BC-breaks between 2.x and 3.x?

### ISSUE THREAD

**Issue by greg0ire** [sensiolabs/SensioGeneratorBundle#473]
Are there any BC-breaks between both versions of this bundle? I could not find any `UPGRADE` file, so I can't figure out why the version number change easily. See https://github.com/sonata-project/SonataAdminBundle/issues/3596

**Comment by HeahDude** [comment]
Closing, ref https://github.com/sonata-project/SonataAdminBundle/pull/3604.
