### ISSUE TITLE
Incorrect variable name for crud generation of a entity which has child naming structure (e.g: AppBundle:Category/EntityName)

### ISSUE THREAD

**Issue by starx** [sensiolabs/SensioGeneratorBundle#478]
If you generate an crud based on entity whose name is `AppBundle:Category/EntityName` on the controller it generates the variable names show as `$category\EntityName` which is a Fatal Error

**Comment by HeahDude** [comment]
Hi @starx! Thanks for reporting this issue. I've opened #508.

**Comment by starx** [comment]
@HeahDude I had created a pull for this issue a long time ago :) 
https://github.com/sensiolabs/SensioGeneratorBundle/pull/479
