### ISSUE TITLE
Incorrect Table Name when generating entity with sub folder e.g. AppBundle:Category\Entity

### ISSUE THREAD

**Issue by starx** [sensiolabs/SensioGeneratorBundle#481]
Similar to #478 when the generator is generating schema for entity with sub folder style e.g. `AppBundle:Category\Entity` the table name used to create becomes `category\entity`.

Thus the table never gets created.

**Comment by ju1ius** [comment]
Also a duplicate of #465

**Comment by javiereguiluz** [comment]
@starx thanks for reporting this issue. As @ju1ius said this is a duplicate of #465, so I'm closing it in favor of the other issue so we can focus our resources. Thanks!

**Comment by starx** [comment]
Oh. Ok, but that issue is closed as well and I have made pull request to
fix it as well.
