### ISSUE TITLE
Incorrect name for Form Type while generation crud based on doctrine entity

### ISSUE THREAD

**Issue by starx** [sensiolabs/SensioGeneratorBundle#482]
If you have a entity like `AppBundle:Category\Entity1` the form type that is used to create the form in the `newAction`, `editAction` becomes something like the following:

```php
$categoryEntity1 = new Entity1();
$form = $this->createForm('AppBundle\Form\Entity1Type', $categoryEntity1);
```

The use statement on top of controller is generated correctly (which is never used because of the wrong name)

```php
use AppBundle\Form\Category\Entity1Type;
```

**Comment by HeahDude** [comment]
Closed by #508.
