### ISSUE TITLE
[RFC] Deprecate the generate:doctrine:crud command

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#488]
*(Disclaimer: I work on a bundle which generates backends for Symfony applications, so there is a notable conflict of interest with this RFC issue. However, I'd propose the same RFC if I didn't work on that bundle)*

---

### Problem

  * This bundle provides lots of useful commands (`generate:bundle`, `generate:command`, etc.) They work great and they are focused on small and well-defined features.
  * However, there is one command (`generate:doctrine:crud`) which is a different story. These are the problems I see with this command:
    * The generated CRUD is disappointing. It lacks almost every feature you expect in a CRUD.
    * We'll never improve this command to generate more complete or advanced CRUDs. We decided to focus on providing just the very basic CRUD features, so you can't expect anything better ... ever.
    * People report lots of "bugs" for the CRUD but we never solve them because they are in fact "feature requests".
    * My feel is that the generated CRUD is far from the quality you expect of anything related to Symfony. It could even hurt our project reputation because most people expect something like the symfony 1 or Django admin generator.
    * In my opinion, using this CRUD as the base of your application is a very bad practice. If you need a CRUD, use any of the third-party bundles which generate much better CRUDs. If your application is much more complex, then forget about the CRUD.

### Solution

  * I propose to deprecate the `generate:doctrine:crud` command and remove it soon from this bundle.
  * What's the alternative? The admin generator bundles provided by the community. There are several well-tested bundles which allow to create Symfony backends in a snap.

**Comment by fabpot** [comment]
I don't see admin generator bundles as a replacement for CRUD generators, they are totally different in their goal. A CRUD is just a way to quickly bootstrap a controller or a set of controllers, it's not about having something that work for all use cases. Not sure what to do here. I don't think we said that we will never improve the current situation and if you have a look at the recent changes, most of them are actually for the CRUD generator. It would help to have a list of features that should be part of the CRUD and see how we could make things work.

**Comment by xabbuh** [comment]
I don't use any of the generate commands Provider by this bundle quite often. So I might miss something. But I tend to agree with @fabpot. The commands provided here serve to generate code skeletons for your application that you then take and tweak as needed while an admin bundle is meant to be used as a ready solution that works out of the box.

**Comment by javiereguiluz** [comment]
Some comments:

  * #382 is the issue where we decided to refocus this bundle and to never change the CRUD generator to make it as useful as an admin generator.
  * @xabbuh all commands are a great starting point ... but I feel `generate:crud` is not. This is just a guess: `generate:crud` is used to bootstrap the backend of the apps (not the public part of the app). Given the third-party bundles out there, using `generate:crud` seems the wrong way to do this because it's too basic and limited.

**Comment by fabpot** [comment]
@javiereguiluz I don't understand why you are comparing a CRUD generator and an admin generator: different tools, different purposes. I would never ever use an admin generator for a CRUD and vice-versa. And your guess is wrong, nobody should ever bootstrap a backend with a CRUD, that does not make sense. And just have a look at Django, you will see that the admin generator is, well, used to generate a backend, not a CRUD for the frontend. To generate frontend code, they have other CRUD tools.

So, again, let make the CRUD generator more useful (if needed) to bootstrap frontend code.

**Comment by javiereguiluz** [comment]
I don't know if it's reliable, but I run a survey on Twitter about this. [The results](https://twitter.com/symfony_en/status/716898728695635968) are depressing:

![generate_doctrine_crud](https://cloud.githubusercontent.com/assets/73419/14273215/275cd204-fb09-11e5-9f7a-f4125061d48c.png)

* ~75% never use it
* ~25% use it as an admin generator
* Nobody uses it to generate frontend code

**Comment by steve-todorov** [comment]
I don't know about others, but I find this feature quite useful. It was quite easy for me to extend the `DoctrineCrudGenerator` class and override only bits which had to be customized like the controller and the views. For the past few years I've been using it as a starting point for creating new CRUD pages fast and easy and then continue to develop more specific code from there.

I strongly believe this feature should be preserved and it should be able to do just the basics - create a form, controller and the views for the methods. For everything more specific people should be extending the classes as I did. One can't expect a CRUD generator to be able to do magic :)

**Comment by javiereguiluz** [comment]
Closing it because this idea didn't gain enough support.

@steve-todorov don't worry, we won't change anything! By the way, there are some Symfony CRUD generators that do magic (e.g. [SonataAdminBundle](https://packagist.org/packages/sonata-project/admin-bundle), [GeneratorBundle](https://packagist.org/packages/symfony2admingenerator/generator-bundle), [EasyAdminBundle](https://packagist.org/packages/javiereguiluz/easyadmin-bundle), etc.)

**Comment by steve-todorov** [comment]
@javiereguiluz thanks for the links! I prefer to write my own code because I mainly work on complicated ERP/CMS platforms with complicated UI and relationships. Nevertheless, these bundles look awesome and I might be able to use them in some less complicated projects! Thanks :)
