### ISSUE TITLE
Generator views wrong place

### ISSUE THREAD

**Issue by omrqs** [sensiolabs/SensioGeneratorBundle#492]
On generate crud, all features (controller, tests and form) are correct path, with exception of views. Also module named has converted to lowercase, mistakenly.

File: `sensio/generator-bundle/Generator/DoctrineCrudGenerator.php`, line 81.

Wrong path:

```php
$dir = sprintf('%s/Resources/views/%s', $this->rootDir, str_replace('\\', '/', strtolower($this->entity)));
```

Then view files are generated under `app/Resources/` and with named lowercase, when must be camelcase.

Fix suggested:

```php
$dir = sprintf('%s/Resources/views/%s', $this->bundle->getPath(), str_replace('\\', '/', $this->entity));
```

**Comment by Ziiweb** [comment]
I find it those paths a bit strange also. I asked about it some days ago: http://stackoverflow.com/questions/37400101/generatedoctrinecrud-generate-templates-at-app-resources-view-myentity-out-of

**Comment by Ziiweb** [comment]
Im my opinion I cannot understand why views are generated at `app/Resources`. I asked about it some [days ago](http://stackoverflow.com/questions/37400101/generatedoctrinecrud-generate-templates-at-app-resources-view-myentity-out-of).

**Comment by xabbuh** [comment]
@Ziiweb This change was done in the SensioGeneratorBundle to conform with the [Symfony Best Practices](http://symfony.com/doc/current/best_practices/templates.html#template-locations).

**Comment by javiereguiluz** [comment]
Closing it as "won't fix". As @xabbuh said, these changes were introduced to comply with the "best practices" of the "modern Symfony apps". The "old way" of doing things will still work in your applications, but this bundle always follows the latest Symfony recommendations.
