### ISSUE TITLE
CRUD generator: deleteAction doesn't work if CSRF protection is disabled

### ISSUE THREAD

**Issue by AlexeyKosov** [sensiolabs/SensioGeneratorBundle#502]
If the delete form doesn't contain a token (i.e. CSRF protection is disabled), the `if ($form->isSubmitted() && $form->isValid()) {` condition always returns `false` and the "delete" action doesn't work.

Symfony 3.1.2

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
