### ISSUE TITLE
Choose between template

### ISSUE THREAD

**Issue by julienfastre** [sensiolabs/SensioGeneratorBundle#505]
Hi,

We make an heavy use of this bundle to generate CRUD. But we encounter a limitation: we use different templates, that we have to manually modify after the generation: we have a template for the admin pages, a template for the user pages, a template for the user pages in some context, ...

We would like to know if it would possible to add an option to choose between template when generating the crud : 

```
php app/console generate:doctrine:crud --entity=AcmeBlogBundle:Post --template=@MyBundle:Resources/views/admin/template
```

And the directory in `MyBundle/Resources/views/admin/template` should look like this : 

```
.
├── actions
│   ├── create.php.twig
│   ├── delete.php.twig
│   ├── edit.php.twig
│   ├── index.php.twig
│   ├── new.php.twig
│   ├── show.php.twig
│   └── update.php.twig
├── config
│   ├── routing.php.twig
│   ├── routing.xml.twig
│   └── routing.yml.twig
├── controller.php.twig
├── tests
│   ├── others
│   │   ├── full_scenario.php.twig
│   │   └── short_scenario.php.twig
│   └── test.php.twig
└── views
    ├── edit.html.twig.twig
    ├── index.html.twig.twig
    ├── new.html.twig.twig
    ├── others
    │   ├── actions.html.twig.twig
    │   └── record_actions.html.twig.twig
    └── show.html.twig.twig
```

If one file is missing, it should be replaced by the one in `GeneratorBundle/Resources/skeleton/crud`.

Will this be useful ? Or is there other possibilities to achieve this feature ?

I made a search amongst past issues and didn't find any issue discussing such feature.

Is this feature desired ?

Having a look at the code, it seems that it would requires to : 
- add an argument to the command, which by default should be  `@SensioGeneratorBundle/Resources/skeleton/crud`
- add an argument to the `DoctrineCrudGenerator` to point to the template (by default, `@SensioGeneratorBundle/Resources/skeleton/crud`)
- prefixing every call to the argument `$template` of the function `renderFile` in `Generator/DoctrineCrudGenerator.php` with the parameter given in the controller.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
