### ISSUE TITLE
Undefined variable passed in crud's new action

### ISSUE THREAD

**Issue by grimmlink** [sensiolabs/SensioGeneratorBundle#515]
Hello,

When generating CRUD, the template for _new_ action doesn't define the entity's variable passed to the template in https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Resources/skeleton/crud/actions/new.php.twig

`'{{ entity_singularized }}' => ${{ entity_singularized }},`

It's only defined if the form is submitted, creating an error on displaying the form on first time.

should add something like 

`${{ entity_singularized }} = new {{ entity }}();` before testing if form is submitted

PS: using 3.0.10

**Comment by HeahDude** [comment]
Hi @grimmlink, thanks for reporting this, I've opened #516 that fixes this regression.

**Comment by fabpot** [comment]
3.0.11 out with the fix

**Comment by grimmlink** [comment]
Thanks
