### ISSUE TITLE
generate:bundle does not generate the right tests directory structure

### ISSUE THREAD

**Issue by juliendufresne** [sensiolabs/SensioGeneratorBundle#530]
Hello,

To my understanding, the tests directory should follow the same structure as the src directory. If we want to test the file `src/Product/AppBundle/Controller/DefaultController.php`we should have a test file located in `tests/Product/AppBundle/Controller/DefaultControllerTest.php`.

This is even more true when using composer autoloading feature.

## Issue
If I'm generating a new bundle using the following command:

```
php bin/console generate:bundle                  \
                  --dir=src                      \
                  --namespace=Product/AppBundle  \
                  --bundle-name=ProductAppBundle \
                  --format=yml
```

It will generate the **good** `src` directory structure:
```
src
└── Product
    └── AppBundle
        ├── Controller
        │   └── DefaultController.php
        ├── ProductAppBundle.php
        └── Resources
            ├── config
            │   ├── routing.yml
            │   └── services.yml
            └── views
                └── Default
                    └── index.html.twig

```

But a **wrong** `tests`directory structure:

```
tests
└── ProductAppBundle
    └── Controller
        └── DefaultControllerTest.php
```
with a **wrong namespace**: `namespace Product\AppBundle\Tests\Controller;`

## Suggestion

The DefaultControllerTest should be located in:
```
tests
└── Product
    └── AppBundle
        └── Controller
            └── DefaultControllerTest.php
```
with the namespace: `Tests\Product\AppBundle\Controller`.

This is not big of an issue for phpunit because it doesn't care much of the tests directory structure.
This is only an issue when you want to use composer autoloading because it can not find the class. 

## Alternative

I don't think it's a good idea but if we want to keep the current test directory structure, we should add a new autoload-dev each time we generate a bundle:
```
"autoload-dev": {
        "psr-4": {
            "Product\\AppBundle\\Tests\\": "tests/ProductAppBundle"
        }
    },
```

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
