### ISSUE TITLE
Erroneous namespace structure generation failed

### ISSUE THREAD

**Issue by Bunkermaster** [sensiolabs/SensioGeneratorBundle#534]
Bug encountered in Sensio Generator Bundle v3.1.2
When creating a new bundle wth generate:bundle command, one of my students entered:
Target Directory [src/]: src/le_gang/

The resulting Bundle used the Bundle name as namespace and ignored the "le_gang" directory altogether. I had to add the le_gang namespace root for the Bundle to be accessible.

![image](https://cloud.githubusercontent.com/assets/4213013/22152462/5c4b8826-df23-11e6-8400-38589e363622.png)

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
