### ISSUE TITLE
Generated code does not comply with the php-cs-fixer @Symfony rule

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#538]
This issue was moved from https://github.com/symfony/symfony/issues/21721

---

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | ^2.7

Code generated by commande line tools like Command or entity generators do not fully respect the rule `Symfony` set by php-cs-fixer.

Most obvious example are phpdoc_summary and trailing_comma_in_multiline_array.

**Comment by fabpot** [comment]
Closing this one. If someone wants to submit a PR, I would be more than happy to merge it.
