### ISSUE TITLE
Entity "%s" does not exist in the "%s" bundle

### ISSUE THREAD

**Issue by ElMijo** [sensiolabs/SensioGeneratorBundle#539]
Hi, I was running the command **doctrine:generate:crud** and I generate the following error

```bash
php bin/console doctrine:generate:crud --entity=SmartMeBaseBundle:Incentivos

[RuntimeException]                                                                                                                                                                                                
  Entity "Incentivos" does not exist in the "SmartMeBaseBundle" bundle. You may have mistyped the bundle name or maybe the entity doesn't exist yet (create it first with the "doctrine:generate:entity" command). 
```
The error is generated in the class **Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory** that does not belong to this package, however, it seemed to me that this issue should also be tracked. [link](https://github.com/doctrine/DoctrineBundle/issues/629).

I also wanted to take the opportunity to suggest adding a parameter that allows you to define in which bundle you want the CRUD to be created, since that error is generated because I am trying to do a CRUD of an entity from a third party bundle, obviously to Create the CRUD this is going to go to that third party bundle and in fact it is needed in a new bundle that will be a component of this third party bundle, and would take the entity bundle as the default bundle, in case the User does not pass any value in this parameter.

The installed version is **doctrine/doctrine-bundle:1.6.7**, **symfony/symfony:3.2.4**, **sensio/generator-bundle:3.1.2**

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
