### ISSUE TITLE
CRUD Controller Imports in one line.

### ISSUE THREAD

**Issue by stepotronic** [sensiolabs/SensioGeneratorBundle#544]
When creating CRUD with write actions the use-statement for Request is added directly after the Route import:
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;use Symfony\Component\HttpFoundation\Request;
I believe it is because of the tokenizing of the two following conditions in the original template.  In my fork i added a {{ "\n" }} in the beginning of line 16 in the "Resources/skeleton/crud/controller.php.twig"

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
