### ISSUE TITLE
generate:bundle doesn't report errors (regression)

### ISSUE THREAD

**Issue by guilliamxavier** [sensiolabs/SensioGeneratorBundle#558]
On a new symfony-standard project, with `composer.json` containing the following lines for autoloading:

```json
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
```

let's generate a new bundle with the command line

```
php bin/console generate:bundle --namespace=BlogBundle --no-interaction
```

on two distinct installs:

1. with vendor sensio/generator-bundle before commit ddf8b6d1f857b17562b1e6e34a81c86a5eb79dd1, e.g. v3.0.11:

![397-a](https://user-images.githubusercontent.com/7404452/28117711-d4c408d2-670e-11e7-9d76-7720a7e3c6d9.png)

i.e. it reports an error _which is expected (see #555)_.

2. with vendor sensio/generator-bundle after commit ddf8b6d1f857b17562b1e6e34a81c86a5eb79dd1, e.g. 3.1.0 (or current v3.1.4):

![397-b](https://user-images.githubusercontent.com/7404452/28117751-f1b9aaa0-670e-11e7-8c41-533f58931203.png)

i.e. it **no longer reports any error**, but any subsequent attempt to boot the app kernel **will still fail**:

![397-b2](https://user-images.githubusercontent.com/7404452/28117762-fa3f79c0-670e-11e7-9e82-c6d59948b074.png)

so that's probably an unintended side effect of PR #397.

---

Note: issue #555 is about the generated bundle not being autoloaded automatically, whereas the present issue is about the command not reporting the error (while it did before).

**Comment by danielgimeno** [comment]
if its helpfull. After creating a new bundle, OOTB installation:

daniel@Pozuelote:~/proyectos/backdoor2/scrumback$ cat composer.json | grep \"symfony/symfony
        "symfony/symfony": "3.3.*",
daniel@Pozuelote:~/proyectos/backdoor2/scrumback$ php bin/console clear:cache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "scrumBundle" from namespace "scrumBundle".
Did you forget a "use" statement for another namespace? in /home/daniel/proyectos/backdoor2/scrumback/app/AppKernel.php:19
Stack trace:
#0 /home/daniel/proyectos/backdoor2/scrumback/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#1 /home/daniel/proyectos/backdoor2/scrumback/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/daniel/proyectos/backdoor2/scrumback/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(137): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/daniel/proyectos/backdoor2/scrumback/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#4 /home/daniel/proyectos/backdoor2/scrumback/ in /home/daniel/proyectos/backdoor2/scrumback/app/AppKernel.php on line 19
daniel@Pozuelote:~/proyectos/backdoor2/scrumback$ 
daniel@Pozuelote:~/proyectos/backdoor2/scrumback$ 
daniel@Pozuelote:~/proyectos/backdoor2/scrumback$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
