### ISSUE TITLE
Symfony 3.3.5 - Can't generate new bundle

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#567]
Moved from https://github.com/symfony/symfony/issues/23623

-----

| Q                | A
| ---------------- | -----
| Bug report?      | mb
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.5

I've just installed new Symfony 3.3.5 project.
Now I'm trying to generate new bundle

`    php bin/console generate:bundle`

But getting this:

>     > Generating a sample bundle skeleton into app/../src/Web/BaseBundle
>       created ./app/../src/Web/BaseBundle/
>       created ./app/../src/Web/BaseBundle/WebBaseBundle.php
>       created ./app/../src/Web/BaseBundle/Controller/
>       created ./app/../src/Web/BaseBundle/Controller/DefaultController.php
>       updated ./app/../tests/WebBaseBundle/Controller/DefaultControllerTest.php
>       created ./app/../src/Web/BaseBundle/Resources/views/Default/
>       created ./app/../src/Web/BaseBundle/Resources/views/Default/index.html.twig
>       created ./app/../src/Web/BaseBundle/Resources/config/
>       created ./app/../src/Web/BaseBundle/Resources/config/services.yml
>       created ./app/../src/Web/BaseBundle/Resources/config/routing.yml
>     > Checking that the bundle is autoloaded
>     FAILED
>     > Enabling the bundle inside app/AppKernel.php
>       updated ./app/AppKernel.php
>     OK

So fixed it in composer.json like this:

```
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
```

also tried like this:

```
    "autoload": {
        "psr-4": { "WebBaseBundle": "src/Web/BaseBundle" },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
```

But if I try to launch my project, I'm getting this error:

> Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to
> load class "WebBaseBundle" from namespace "Web\BaseBundle". Did you
> forget a "use" statement for another namespace? in
> /Volumes/U/Projects/e-shop/app/AppKernel.php on line 18

Here is my AppKernel

```
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new Web\BaseBundle\WebBaseBundle(),
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();

            if ('dev' === $this->getEnvironment()) {
                $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
                $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
            }
        }

        return $bundles;
    }
```

What can be possibly wrong in totally new project? 
Thanks for help.

**Comment by xabbuh** [comment]
The namespace in the `autoload` section needs to be `Web\BaseBundle` instead of `WebBaseBundle`.

**Comment by kironet** [comment]
Also tried.

**Comment by guilliamxavier** [comment]
@kironet From [the latest docs](https://symfony.com/doc/master/bundles/SensioGeneratorBundle/commands/generate_bundle.html):

1. a correct line is:
    ```
        "psr-4": { "Web\\BaseBundle\\": "src/Web/BaseBundle" },
    ```
2. then you need to execute a
    ```
    composer dump-autoload
    ```

---

Notes about the `"Web\\BaseBundle\\"` key:

- it's a JSON string, so any literal backslash must be backslash-escaped (i.e. doubled)
- Composer insists that "A non-empty PSR-4 prefix must end with a namespace separator", hence the trailing `\\`

Also, doing a `composer install` implicitly does a `dump-autoload`.

**Comment by oldeb** [comment]
Any news on this issue ? 
It is very disturbing especially for newbies who are following basic tutorials.

**Comment by bouloan** [comment]
The solution given by guilliamxavier does not work for me, 

if try to execute "composer dump-autoload", I got a message which indicate that "composer" is not recognised as a command applet name.

**Comment by bouloan** [comment]
OK, the solution proposed by guilliamxavier but firstly you need to download 'composer' tool on this address:   (https://getcomposer.org/)

**Comment by tseho** [comment]
Still happening with a fresh install of symfony 3.4.0-RC1 because the default autoload in composer.json is:

```
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
```

The autoloading on "src" does not exists by default, what could be done to at least warn the users about it ?

**Comment by dsjproductions** [comment]
Change the autoload section to:

```     
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
```

And then run 
`composer dump-autoload`

**Comment by javiereguiluz** [comment]
Closing this old issue because an alternative solution has been provided in the previous comment. Thanks.

**Comment by maryamgh5** [comment]
j'ai eu cette problème lors de l’installation d'un nouveau base de donnée 
![Capture](https://user-images.githubusercontent.com/43962924/59093905-e5d40100-890c-11e9-9869-f1074b0d246c.PNG)

**Comment by maryamgh5** [comment]
quelqu'un peut m'aider ?

**Comment by xabbuh** [comment]
Please use one of the [support channels](https://symfony.com/support) to get help with your issue and also please ask in English there as not everyone speaks French.
