### ISSUE TITLE
Use 'kernel.project_dir' instead of 'kernel.root_dir/../' in GenerateBundleCommand

### ISSUE THREAD

**Issue by KintradimCrux** [sensiolabs/SensioGeneratorBundle#568]
Hello,

to improve support for non-standard directory layouts i suggest using the 'kernel.project_dir' container parameter instead of the parent directory of 'kernel.root_dir' as $projectRootDirectory in GenerateBundleCommand::createBundleObject().  Using 'kernel.root_dir' could result in wrongly placed bundle files.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
