### ISSUE TITLE
Wrong generated CRUD for entities with similar names (i.e. Node, NodeTree)

### ISSUE THREAD

**Issue by cisatchmo** [sensiolabs/SensioGeneratorBundle#569]
php bin/console generate:doctrine:crud
The Entity shortcut name: AcmeBundle:Node
Do you want to generate the "write" actions [no]? yes
Configuration format (yml, xml, php, or annotation) [annotation]:
Routes prefix [/nodetree]: /node              <------------------------------------------that's not good 

Summary before generation

You are going to generate a CRUD controller for "AcmeBundle:NodeTree"
using the "annotation" format.

Do you confirm generation [yes]?

**Comment by cisatchmo** [comment]
I solved the problem gentating in order entities by longer to shorter names: NodeTree --> Node ---> ...
Is there a better way to do it?

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
