### ISSUE TITLE
Generating an entity without bundle name in flex project!

### ISSUE THREAD

**Issue by muzfr7** [sensiolabs/SensioGeneratorBundle#570]
As bundle approach is not preferred in flex project, i was wondering how do you generate an entity in flex project without providing bundle name? cannot say it's an issue though!!

**Comment by chapterjason** [comment]
Also noticed that issue with a flex project and found this issue https://github.com/sensiolabs/SensioGeneratorBundle/issues/335

**Comment by muzfr7** [comment]
Currently entity generator is tightly coupled with Bundle Namespace to generate an entity e-g: `$bundle->getName() => $bundle->getNamespace().'\\Entity'`.

I updated it myself to support bundle-less applications, so if bundle name was not provided, it generates entity in `symfony_blog/src/Entity` rather than `symfony_blog/src/AppBundle/Entity`.

**Comment by sadikoff** [comment]
Tried to update this bundle to work with flex properly. There is a lot of work to do, but with last commit seems that all works as needed. Don't know if my code is good enough to create pull request, but if someone need here it is: [https://github.com/sadikoff/SensioGeneratorBundle](sadikoff/flex-generator-bundle) For now it uses original sensio namespaces, I just removed bundle dependency on code generation.

**Comment by muzfr7** [comment]
@sadikoff - nice effort, however should bundle dependency be removed completely? 
What about some extra sugar on existing commands, so we can choose either to generate in or out of bundle..

**Comment by sadikoff** [comment]
@muzfr7 I think yes, it should be removed for flex projects.
At first i decided to do it with "App" prefix without "Bundle, and generate compatible code. But after installing flex demo app, changed my opinion and removed bundle dependency at all.

Without this dependency we get cleaner code and everything is generated in new flex-way.

**Comment by muzfr7** [comment]
I agree when it come to flex, but i am still wondering if bundle-less approach is going to be the way to create symfony applications from now on..

**Comment by sadikoff** [comment]
Agreed.

Sincerely I didn't like bundles from the beginning. I think it complicated the code and for now flex can fix it.

**Comment by aik099** [comment]
Any PR coming?

Here are my ideas:

1. detect if we're using flex or not (e.g. check for `config/bundles.php` file presence)
2. when flex detected, then:

* instead of placing file into `src/BundleName/Command/...` place it into `src/Command/...`
* instead of using `BundleName\Command` namespace use `App\Command` namespace
* allow entering empty bundle name or don't allow entering it at all, because in bundle-less folder structure you can have multiple bundles under `src` folder anyway

**Comment by sadikoff** [comment]
@aik099 I think we don't need to detect flex we need to use prefixes.
for example:
bundle-way:
`bin/console generate:controller AppBundle:ControllerName`
flex-way:
`bin/console generate:controller ControllerName`
or without "Bundle" word
`bin/console generate:controller App:ControllerName`
to use right namespace for generation

**Comment by aik099** [comment]
I agree. This won't work out of the box though, because `bin/console generate:controller App:ControllerName` would put file in in `/src/App/Controller` folder and not in `/src/Controller` folder.

Also when command is executed without arguments we need to allow skipping step (or allowing an empty value) for question about bundle name.

**Comment by muzfr7** [comment]
I also prefer to keep it for both flex and non-flex application, probably same like @aik099 suggested.

**Comment by aik099** [comment]
Without this being implemented one way or another it doesn't make sense, because after Symfony 4.0 release at the end of November this bundle would be placing generated files in wrong namespaces/folders which would make it a pain to use.

**Comment by sadikoff** [comment]
It can be implemented by 2 bundles one for flex and one for bundle way

**Comment by muzfr7** [comment]
Agreed, it is important because there are so many application using this bundle, including 2, 3 mine using Symfony 3..

**Comment by muzfr7** [comment]
@sadikoff i don't prefer 2 bundle approach, while 1 bundle can do that..

**Comment by sadikoff** [comment]
@muzfr7 but you will have one big bundle with a lot of code for compatibility between flex and non-flex as a result. I don't think this way is good enough.

**Comment by muzfr7** [comment]
@sadikoff let's get more votes then..

**Comment by aik099** [comment]
> ... but you will have one big bundle with a lot of code for compatibility between flex and non-flex as a result. I don't think this way is good enough.

@muzfr7 , not sure if there be really `lots of code` for compatibility. I think we need to try implementing this and see what happens.

**Comment by muzfr7** [comment]
@aik099 true, and will show something asap..

**Comment by aik099** [comment]
Looking into code of this bundle I've found, that it's created around `Bundle` class, which has `getPath` and `getNamespace` methods that work based on location of bundle class.

To make it work as expected I've did this:

1. create `src/App.php` file with `App\App` class that extends `Symfony\Component\HttpKernel\Bundle\Bundle`
2. added `'App\App' => ['all' => true],` to the array returned from `config/bundles.php` file 
3. used `App` as bundle name when asked by generator command

**Comment by sadikoff** [comment]
Not all generated code will work as expected in flex project with such implementation.

**Comment by aik099** [comment]
I've tested on `generate:command` command only. Any specific command that doesn't work for you?

**Comment by sadikoff** [comment]
generate:crud/controller there is route problems and template loading sometimes has issues

**Comment by kironet** [comment]
any update?

**Comment by sadikoff** [comment]
updated my code to work with flex sf3.4/4.0 but haven't tested it yet. If someone wants to help, you are welcome =) `composer req sadikoff/flex-generator-bundle`

**Comment by aik099** [comment]
Please post a link to a pr/diff so that we can review the changes made.

**Comment by sadikoff** [comment]
diff: https://github.com/sensiolabs/SensioGeneratorBundle/compare/master...sadikoff:master

need some more time to optimize everything and test all functionality

**Comment by pixocode** [comment]
@aik099 it works perfectly, thank you very much

**Comment by kironet** [comment]
Yeah, doctrine:generate:entities App works, but it's not generating getters and setters Entity...

**Comment by sadikoff** [comment]
`doctrine:generate:entities` is not part of this bundle. It's belongs to doctrine-bundle.

**Comment by fabpot** [comment]
symfony/maker-bundle should be used instead now. There is an issue opened there about CRUD, so, closing this one.
