### ISSUE TITLE
Twig Templates directory, best practice ?

### ISSUE THREAD

**Issue by acidjames** [sensiolabs/SensioGeneratorBundle#571]
Hi all,

first off, thanks for this bundle that i've been using for a few years now. 

One thing i don't get (i searched before), is : why are the twig files now generated in the app/ directory ?

What is the purpose behind ? I suppose it should now be considered a best practice ?

Thanks in advance,
James 🏯

**Comment by xabbuh** [comment]
see http://symfony.com/doc/current/best_practices/templates.html#template-locations
