### ISSUE TITLE
Putting views inside bundle

### ISSUE THREAD

**Issue by pmpr-ir** [sensiolabs/SensioGeneratorBundle#576]
| Symfony                            | **3.3.9** |
| ------------------------- | --------- |
| **SensionGeneratorBundle** | **3.1.6** |

# Feature request

According to line **83** of `\Sensio\Bundle\GeneratorBundle\Generator\DoctrineCrudGenerator` which is:

```
$dir = sprintf('%s/Resources/views/%s', $this->rootDir, strtolower($entity));
```
One, can not put views and other resources, in some other location, like the bundle itself:

```
AppBundle/Resources/views
```
I think It should be customisable. Please add this feature if possible.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
