### ISSUE TITLE
Naming strategy is ignored for table names?

### ISSUE THREAD

**Issue by vpArth** [sensiolabs/SensioGeneratorBundle#577]
https://github.com/sensiolabs/SensioGeneratorBundle/blob/8ed13441e69fa0674fe3b2c69861be6d60bf5cb3/Generator/DoctrineEntityGenerator.php#L77

Why `Inflector::tableize` is used for table name generation?
We have `NamingStrategy::classToTableName` for this, isn't it?

As a result we always have snake_case table names, ignoring any namingStrategy configured..

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
