### ISSUE TITLE
Command auto-registration is deprecated since Symfony 3.4

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#578]
Spotted while running tests in an app upgraded to Symfony 3.4:

```
Auto-registration of the command
"Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineFormCommand" is
deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based
service discovery instead:.
```

Same for:

* `Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineEntityCommand`
* `Sensio\Bundle\GeneratorBundle\Command\GenerateDoctrineCrudCommand`
* `Sensio\Bundle\GeneratorBundle\Command\GenerateControllerCommand`
* `Sensio\Bundle\GeneratorBundle\Command\GenerateCommandCommand`
* `Sensio\Bundle\GeneratorBundle\Command\GenerateBundleCommand`

**Comment by Umkus** [comment]
I'm having the same issue.
Temporarily silenced by `error_reporting=E_ALL & ~E_DEPRECATED`

**Comment by mkingbe** [comment]
same issue, is there any nice fix ?

**Comment by TerjeBr** [comment]
I also get this deprication warning. Is anyone working on this?

**Comment by mkingbe** [comment]
I think you need to switch to https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html
as accordingly to the documentation the maker bundle is the alternative version for generator bundle in symfony 3.4 and above.

**Comment by chucky2305** [comment]
Thanks @mkingbe ! you saved me here!!

**Comment by javiereguiluz** [comment]
Closing because this bundle should no longer be used in new Symfony apps. Use [Maker Bundle](https://github.com/symfony/maker-bundle) instead. Thanks!

**Comment by ghalusa** [comment]
@javiereguiluz - Closing this issue _may not be the ideal move_.

When creating a new Symfony project using v3.4.14, composer.json is still populated with the `sensio/generator-bundle` under `require-dev`.

**composer create-project**

```
composer create-project symfony/framework-standard-edition symfony_test "3.4.*"
```

**composer.json**

```
"require-dev": {
  "sensio/generator-bundle": "^3.0",
  ...
```

**Comment by fatonh** [comment]
I think these errors are causing my custom symfony commands not registered. I'm running symfony v.3.4.30. Has anyone else had similar case?

**Comment by OskarStark** [comment]
Can you please show one of your command?

**Comment by fatonh** [comment]
Here it is some of the configuration for my command 
 /**
    * Configure command
    */
   protected function configure()
   {
       $this
           // the name of the command (after "bin/console")
           ->setName('app:fetch-ga')
           // the short description shown while running "php bin/console "
           ->setDescription('Fetch google analytics')
           ...
           
           // the full command description shown when running the command with
           // the "--help" option
           ->setHelp("This command allows you to fetch google analytics. 
           Usage: php bin/console app:fetch-ga ");
   }

**Comment by OskarStark** [comment]
Can you please show the class definition? Pleas epost the whole command without the execute() method.

**Comment by fatonh** [comment]
<?php

namespace AppBundle\Command;

use AppBundle\Entity\Task;
use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use TweedeGolf\PrometheusClient\CollectorRegistry;

class AppToolCommand extends ContainerAwareCommand
{

    private $uid;
    private $em;
    /** @var Task */
    private $task;
    /** @var OutputInterface */
    private $output;
    /** @var CollectorRegistry */
    private $collector;

    /**
     * AppAdminToolTaskCommand constructor.
     * @param CollectorRegistry $collector
     * @param string|null $name
     */
    public function __construct(CollectorRegistry $collector, ?string $name = null)
    {
        // inject Prometheus\CollectorRegistry service to observe metrics
        $this->collector = $collector;

        parent::__construct($name);
    }

    /**
     * Configure command
     */
    protected function configure()
    {
        $this
            // the name of the command (after "bin/console")
            ->setName('app:fetch-ga')
            // the short description shown while running "php bin/console "
            ->setDescription('Fetch google analytics')
            ->setDefinition(
                // some definition here
            )
            ->addOption('option', null, InputOption::VALUE_NONE, 'Option description')
            // the full command description shown when running the command with
            // the "--help" option
            ->setHelp("This command allows you to fetch google analytics. 
        
    }

  

    /**
     * init function
     */
    private function init()
    {
        $this->em = $this->getContainer()->get('doctrine')->getManager();

        $this->task = $this->em->getRepository('AppBundle:Task')->find($this->uid);

    }

  
}

**Comment by OskarStark** [comment]
can you please add `protected static $defaultName = 'app:fetch-ga';`

**Comment by fatonh** [comment]
Yes. I have spotted that in the new changes in the documentation on how to create symfony commands. But no luck.  And I had to run "composer install" to see the command on the list and not just editing the class.
