### ISSUE TITLE
Does not work with Symfony 4.0

### ISSUE THREAD

**Issue by PolywickStudio** [sensiolabs/SensioGeneratorBundle#583]
composer require sensio/generator-bundle

Using version ^3.1 for sensio/generator-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install sensio/generator-bundle v3.1.5|remove symfony/process v4.0.0

**Comment by fabpot** [comment]
Indeed, this bundle is not compatible with 4.0. You should use symfony/maker-bundle instead.

**Comment by ksn135** [comment]
@fabpot how to generate CRUD with symfony/maker-bundle ?

**Comment by alexiswbr** [comment]
Even without any CRUD generator, I really wonder how to generate a bundle (for sharing purpose, I know this is not the recommended way to use Symfony now)
