### ISSUE TITLE
Symfony 4 use

### ISSUE THREAD

**Issue by petforsberg** [sensiolabs/SensioGeneratorBundle#589]
This is the Symfony 4 docs:

https://symfony.com/doc/current/bundles.html

specifically this part:

https://symfony.com/doc/current/bundles.html#creating-a-bundle

which states:

`php bin/console generate:bundle --namespace=Acme/TestBundle`

However, the `generate:bundle` command has not become a built-in Symfony 4 command, still this bundle is available for 2 and 3 versions only: https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/composer.json#L14

How can I automatically generate a bundle in Symfony 4? Or, will it be possible to include Generator in Symfony 4?

**Comment by fabpot** [comment]
This bundle does not support Symfony 4. It also does not support the new bundle-less directory structure as created by Symfony Flex. Use the [Maker bundle](https://github.com/symfony/maker-bundle) instead.
