### ISSUE TITLE
bin/console generate:controller generates test class not in standard directory

### ISSUE THREAD

**Issue by Mynyx** [sensiolabs/SensioGeneratorBundle#594]
If generating a new controller (for example AppBundle:Example)  with ````bin/console generate:controller````, the test class is generated as ````./src/AppBundle/Tests/Controller/ExampleControllerTest.php```` and not in the standard directory ````./tests/AppBundle/Controller/````, where the ````DefaultControllerTest.php```` is located. This could be confusing.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
