### ISSUE TITLE
Make the output quiet during tests

### ISSUE THREAD

**Issue by greg0ire** [sensiolabs/SensioGeneratorBundle#598]
![untitled](https://user-images.githubusercontent.com/657779/51085457-d70c6800-1739-11e9-8a2f-9f9bc679e423.png)

Help! I cannot seem to be able to make the output normal when running tests that use this bundle. There does not seem to be away to change the output with some spy, or black hole output: https://github.com/sensiolabs/SensioGeneratorBundle/blob/28cbaa244bd0816fd8908b93f90380bcd7b67a65/Generator/Generator.php#L96

What tricks do you usually use for this? cc @OskarStark @kunicmarko20 @core23

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
