### ISSUE TITLE
Sensio Method and Route are deprecated

### ISSUE THREAD

**Issue by madmath03** [sensiolabs/SensioGeneratorBundle#600]
The following deprecation appear after generating CRUD:

> The “Sensio\Bundle\FrameworkExtraBundle\Configuration\Route” annotation is deprecated since version 5.2. Use “Symfony\Component\Routing\Annotation\Route” instead
> The “Sensio\Bundle\FrameworkExtraBundle\Configuration\Method” annotation is deprecated since version 5.2. Use “Symfony\Component\Routing\Annotation\Route” instead.

Coming from there:
https://github.com/sensiolabs/SensioGeneratorBundle/blob/28cbaa244bd0816fd8908b93f90380bcd7b67a65/Resources/skeleton/crud/controller.php.twig#L12

The annotations of methods will also need to be updated from 
```php
    /**
     * @Route("/something")
     * @Method({"VERB"})
     */
```
to 
```php
    /**
     * @Route(path="/something", methods={"VERB"})
     */
```

**Comment by fabpot** [comment]
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.
