### ISSUE TITLE
Proposal: Remove DependencyInjection dir

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioGeneratorBundle#67]
Hey guys!

I'd like to propose that the bundle generator does *not* generate a `DependencyInjection` directory. My thoughts are that creating a DI extension class is an advanced thing, and that most end-users should simply be importing DI resource config files directly from `config.yml`. Furthermore, I think - like routing config - that we should teach that just one config file is loaded by symfony and that you must import all other resources from that file. Having a DI extension that automatically loads a `services.xml` clouds this.

Thanks!

**Comment by javiereguiluz** [comment]
This issue can be closed because #312 was already merged.
