### ISSUE TITLE
CRUD Generator and joined entities

### ISSUE THREAD

**Issue by Dentxinho** [sensiolabs/SensioGeneratorBundle#81]
If you generate a CRUD for an entity that have relationships, the generator don't generate the information of joined entities on the `show` view.
Looking into it, i've found that `generateShowView` method renders `show` skeleton passing the variable `fields` with the value of `fieldMappings` (from the class metadata). Joined entities are inside `associationMappings`. The generator should do some logic to merge `fieldMappings` with `associationMappings` to pass them to the skeleton.

**Comment by javiereguiluz** [comment]
Recently we decided to refocus the purpose of this bundle and work only on its core features. Supporting entity associations is one of the features that we prefer to not implement yet. The alternative solution is to use third-party bundles such as SonataAdmin, which support this and many other complex features.

Therefore, I'm closing this and all the other related issues and pull requests as "won't fix". Thanks for understanding it.
