### ISSUE TITLE
Report added/modified/deleted files

### ISSUE THREAD

**Issue by lmcd** [sensiolabs/SensioGeneratorBundle#9]
I love the convenience of things like the interactive generator, but have a little anxiety/distrust for what they are doing behind the scenes. It always puts my mind at ease when I can see which files were added, modified or deleted.

Perhaps we should add this to the terminal output when running the generators?

**Comment by javiereguiluz** [comment]
Is this feature still desired? It should not be that hard to implement it.

**Comment by weaverryan** [comment]
@javiereguiluz I don't agree that it should require a `-v` flag. Beginners probably need to know what files are modified more than anyone, and they won't know about the `-v` flag (nor could they simply re-run the command after with `-v`).
